# FashionIQ Iterative Training Configuration

# Model Configuration
model_backbone: "qwen2_vl"
model_path: ""  # Path to pretrained VLM2Vec model
foundation_model_path: ""  # Path to foundation model (e.g., Qwen2-VL-2B-Instruct)
foundation_model_backbone: "qwen2_vl"

# Dataset Configuration
dataset_name: "fashioniq"
data_dir: "./data/FashionIQ"
image_base_dir: "./data/FashionIQ/images"
categories: ["dress", "shirt", "toptee"]

# Training Configuration
num_iterations: 3
hard_negative_k: 5
batch_size: 32
learning_rate: 1e-5
num_epochs: 5
warmup_ratio: 0.1
weight_decay: 0.01
gradient_accumulation_steps: 1
max_grad_norm: 1.0

# Optimization
optimizer: "adamw"
scheduler: "cosine"
fp16: true
dataloader_num_workers: 4

# Iterative Training Specific
fast_mode: false  # Set to true for quick testing
auto_resume: false  # Auto resume from latest checkpoint
save_strategy: "epoch"
save_total_limit: 3
logging_steps: 50
eval_steps: 500

# Experiment Configuration
experiment_dir: "./experiments"
exp_suffix: ""  # Optional suffix for experiment name
output_dir: "./outputs/fashioniq_iterative"
logging_dir: "./logs/fashioniq_iterative"
run_name: "fashioniq_iterative_training"

# Hardware Configuration
per_device_train_batch_size: 8
per_device_eval_batch_size: 16
gradient_checkpointing: true
ddp_find_unused_parameters: false

# Evaluation Configuration
eval_dataset: "fashioniq_test"
eval_batch_size: 64
metric_for_best_model: "recall_at_1"
greater_is_better: true
evaluation_strategy: "steps"

# Foundation Model Configuration
foundation_model_dtype: "auto"
foundation_model_device_map: "auto"
foundation_max_new_tokens: 100
foundation_temperature: 0.7
foundation_top_p: 0.9

# Fashion-specific settings
fashion_categories: ["dress", "shirt", "toptee"]
category_specific_training: false  # Train on all categories together

# Advanced Settings
use_lora: false
lora_r: 16
lora_alpha: 32
lora_dropout: 0.1
deepspeed_config: null
report_to: ["wandb"]
wandb_project: "fashioniq_iterative_training"
