# FashionIQ Dataset Configuration for Iterative Training - FAST MODE

FashionIQ:
    dataset_parser: IterativeFashionIQDataset
    dataset_name: FashionIQ  # local FashionIQ data
    dataset_split: train
    data_dir: /home/guohaiyun/yty_data/FashionIQ  # base directory (should contain images/ and captions/)
    image_base_dir: /home/guohaiyun/yty_data/FashionIQ  # base directory for images
    weight: 1.0
    
    # Iterative training specific configs
    max_iterations: 3
    hard_neg_collection_freq: 1
    hard_neg_top_k: 10
    caption_generation_batch_size: 8
    
    # Fast mode settings - ENABLED for quick testing
    fast_mode: true           # Enable fast mode
    fast_mode_max_samples: 200  # Limit samples for hard negative mining per round
    fast_mode_retrieval_db_size: 1000  # Subset candidate pool for quick retrieval
    fast_mode_max_steps: 20    # Minimal steps per iteration
    
    # Foundation model for caption generation (optional)
    foundation_model_name: "/home/guohaiyun/yangtianyu/CPRCIR/checkpoints/hf_models/Qwen2-VL-7B-Instruct"
    foundation_model_temperature: 0.7
    foundation_model_max_length: 128
