# Test Iterative Training Configuration
# This configuration is for quick testing and debugging

# Model Configuration
model_backbone: "qwen2_vl"
model_path: ""  # Path to pretrained VLM2Vec model
foundation_model_path: ""  # Path to foundation model (optional for testing)
foundation_model_backbone: "qwen2_vl"

# Dataset Configuration
dataset_name: "cirr"
data_dir: "./data/CIRR"
image_base_dir: "./data/CIRR"
captions_file: "./data/CIRR/cirr_captions_train.json"
image_splits_file: "./data/CIRR/cirr_image_splits.json"

# Training Configuration - Reduced for quick testing
num_iterations: 2  # Reduced for testing
hard_negative_k: 3  # Reduced for testing
batch_size: 4  # Small batch for testing
learning_rate: 1e-5
num_epochs: 1  # Single epoch for testing
warmup_ratio: 0.1
weight_decay: 0.01
gradient_accumulation_steps: 1
max_grad_norm: 1.0

# Optimization
optimizer: "adamw"
scheduler: "cosine"
fp16: true
dataloader_num_workers: 2  # Reduced for testing

# Iterative Training Specific
fast_mode: true  # Enable fast mode for testing
auto_resume: false
save_strategy: "epoch"
save_total_limit: 2  # Keep fewer checkpoints
logging_steps: 10  # More frequent logging for testing
eval_steps: 50  # More frequent evaluation

# Experiment Configuration
experiment_dir: "./experiments/test"
exp_suffix: "test"
output_dir: "./outputs/test_iterative"
logging_dir: "./logs/test_iterative"
run_name: "test_iterative_training"

# Hardware Configuration
per_device_train_batch_size: 2  # Very small for testing
per_device_eval_batch_size: 4
gradient_checkpointing: true
ddp_find_unused_parameters: false

# Evaluation Configuration
eval_dataset: "cirr_test"
eval_batch_size: 8  # Small batch for testing
metric_for_best_model: "recall_at_1"
greater_is_better: true
evaluation_strategy: "steps"

# Foundation Model Configuration
foundation_model_dtype: "auto"
foundation_model_device_map: "auto"
foundation_max_new_tokens: 50  # Shorter for testing
foundation_temperature: 0.7
foundation_top_p: 0.9

# Test-specific settings
max_samples_per_iteration: 50  # Limit samples for quick testing
debug_mode: true
verbose_logging: true

# Advanced Settings
use_lora: false
deepspeed_config: null
report_to: []  # Disable wandb for testing
wandb_project: null
